{
  "formatVersion": "1.1",
  "component": {
    "group": "com.paxus.ui",
    "module": "constant",
    "version": "1.03.00T_20251211",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "constant-1.03.00T_20251211.jar",
          "url": "constant-1.03.00T_20251211.jar",
          "size": 48771,
          "sha512": "f781cd1bfb02981772d46aabb7fa2dbf7f332916caee2bfdc67d6faed62fe294cea22fbd1d02c29d6665488a5ec0110fe27e65ee8ba82b3ccf3dd2441ac29d3e",
          "sha256": "1a4ec1fb32692b7a65fee889786bb0ca3e1dc63bd33f92a6b3f6f65a0f1006c7",
          "sha1": "19a1fbb709d0d31a30a65582ad38e565bc85b8c6",
          "md5": "8990bd4069a1465c9be5ee30f2c2ad5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "constant-1.03.00T_20251211.jar",
          "url": "constant-1.03.00T_20251211.jar",
          "size": 48771,
          "sha512": "f781cd1bfb02981772d46aabb7fa2dbf7f332916caee2bfdc67d6faed62fe294cea22fbd1d02c29d6665488a5ec0110fe27e65ee8ba82b3ccf3dd2441ac29d3e",
          "sha256": "1a4ec1fb32692b7a65fee889786bb0ca3e1dc63bd33f92a6b3f6f65a0f1006c7",
          "sha1": "19a1fbb709d0d31a30a65582ad38e565bc85b8c6",
          "md5": "8990bd4069a1465c9be5ee30f2c2ad5d"
        }
      ]
    }
  ]
}
